#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server

#Accept 4 parameters display Usage...
if [ $# -ne 4]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path=$1
server_id=$2
username=$3
ssh_key_path=$4

#transfer file with scp
scp -o "StrictHostKeyChecking no" -i $ssh_key_path $file_path $username@$server_ip:~

echo "File Transfer successful!"
