#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server's active IPv4 IPs
# Write a bash script that configures a server to the above requirements
# Solutions: delete existing file ../sites-enabled/default and replace it with the copy. And you will be create a symbolic link

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
