#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it's executed on.
#ifconfig | grep -Po '(?<=inet addr:)(?:[0-9]{1,3}\.){3}[0-9]{1,3}'

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1

